### ISSUE TITLE
Some Question about how to get the key from game

### ISSUE THREAD

**Issue by Nakasu-ksm** [tellowkrinkle/SxamTools#1]
Hi, Are you using ida to get the key? I found that Higurashi-mei games make some string random so I cannot understand what they mean. Can you give me some tips? Thank you.

**Comment by Nakasu-ksm** [comment]
Got it Thank you!

**Comment by TellowKrinkle** [comment]
For anyone else:
I used ghidra with [Il2CppDumper](https://github.com/Perfare/Il2CppDumper)

It was in `Sxam.Setting_TypeInfo->static_fields->DecodeKey`, which was initialized in `Sxam.Setting$$ctor` and passed to `Sxam.Crypto$$Decode`

If you can't get symbols working, you can try searching for `movk`s of the fnv hash constants, as the decryption function did the decryption and hashing in one

**Comment by Nakasu-ksm** [comment]
Yes for 

> For anyone else: I used ghidra with [Il2CppDumper](https://github.com/Perfare/Il2CppDumper)
> 
> It was in `Sxam.Setting_TypeInfo->static_fields->DecodeKey`, which was initialized in `Sxam.Setting$$ctor` and passed to `Sxam.Crypto$$Decode`
> 
> If you can't get symbols working, you can try searching for `movk`s of the fnv hash constants, as the decryption function did the decryption and hashing in one

Tips: GPCECLBCIGO is the new function name for Sxam.Setting
However, the game key didn't change although they changed all function names.
